### ISSUE TITLE
dbatools dashboard does not refresh

### ISSUE THREAD

**Issue by aftabkhan001** [Glial/PmaControl#15]
dbatools dashboard has not been refreshed since earlier this morning:

Last refresh : June 12 2015 06:19:16 UTC

How could we refresh dashboard?

**Comment by Esysteme** [comment]
well try : 

/etc/init.d/glial/stop
or look on screen

try to run manually : glial pma_cli all (you could see witch server is blocking daemon)

It some case when MySQL keep connection and do nothing (no error and no answer) with it can happen, (when server with no more space for data/binlog)

**Comment by Esysteme** [comment]
in 0.8 the collect of data will be multithreaded and non blocking to prevent this case.

**Comment by aftabkhan001** [comment]
I do not see any connections in database:

~$ mysql -hdba-tools-sa-01 -udba -p -e"show processlist;"
Enter password:
+---------+-----------------+--------------------+------+-------------+---------+------------------------+------------------+----------+
| Id      | User            | Host               | db   | Command     | Time    | State                  | Info             | Progress |
+---------+-----------------+--------------------+------+-------------+---------+------------------------+------------------+----------+
|       2 | event_scheduler | localhost          | NULL | Daemon      | 6823344 | Waiting on empty queue | NULL             |    0.000 |
| 1730048 | replication     | 10.16.60.254:50349 | NULL | Binlog Dump |   15376 | Writing to net         | NULL             |    0.000 |
| 1731723 | dba             | 127.0.0.1:49550    | NULL | Query       |       0 | init                   | show processlist |    0.000 |
+---------+-----------------+--------------------+------+-------------+---------+------------------------+------------------+----------+

**Comment by aftabkhan001** [comment]
We tried  glial pma_cli all

no issues

**Comment by aftabkhan001** [comment]
Earlier today, we tried to restart dbatools:

 /etc/init.d/gliald stop
Stopping Daemon for my magnificent PHP CLI script: start-stop-daemon: warning: failed to kill 14013: No such process
1 pids were not killed
No process in pidfile '/var/run/gliald.pid' found running; none killed.

**Comment by Esysteme** [comment]
New Daemon in 0.8. This case cannot happen anymore
