### ISSUE TITLE
Date / heure dernier refresh

### ISSUE THREAD

**Issue by NOLEGGINI** [Glial/PmaControl#31]
Serait-il possible de mettre en place l'information du dernier "refresh" de la liste des serveurs ? (quand le dernier "agent testallmysql" a été effectué ?

**Comment by Esysteme** [comment]
Salut Nico, 

j'y avais déjà pensé, ça sera bon dans la prochaine version =)

**Comment by Esysteme** [comment]
ça sera présent dans la version 0.8
