### ISSUE TITLE
failed git clone

### ISSUE THREAD

**Issue by umarzuki** [Glial/PmaControl#48]
when I tried to git clone

# git clone git@github.com:Glial/PmaControl.git pmacontrol
Cloning into 'pmacontrol'...
The authenticity of host 'github.com (192.30.253.113)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by Esysteme** [comment]
you can use : https://github.com/Glial/PmaControl.git instead.

fixed on documentation
