### ISSUE TITLE
no manual on adding database servers

### ISSUE THREAD

**Issue by umarzuki** [Glial/PmaControl#50]
When I clicked add server, it I could not type in new IP address accept for one already configured during install.

**Comment by Esysteme** [comment]
for the moment default way to add a server : 

edit config file : pmacontrol/configuration/db.config.ini.php

add a server as : 

[server_name]
driver=mysql
hostname=10.0.0.1
port=3306
user=root
password='passwordroot'
database=mysql

once it's done run : 

./glial agent updateServerList
